# Generated by Django 4.0.4 on 2022-06-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecream', '0002_alter_testuserdata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuserdata',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
